import {Dimensions, StyleSheet} from 'react-native';
import {COLORS} from '../../../assets/colors';
import {globalStyles} from '../../../assets/globalStyles.styles';

export const styles = StyleSheet.create({
  mainContainer: {
    borderWidth: 1,
    borderColor: '#eaeaea',
    alignItems: 'center',
    borderRadius: 4,
    backgroundColor: 'white',

    marginLeft: 4,
    width: Dimensions.get('window').width / 2 - 7,
    marginTop: 5,
    minHeight: 340,
  },
  imageContainer: {
    width: Dimensions.get('window').width / 2 - 7,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  imageStyle: {
    height: 200,
    width: Dimensions.get('window').width / 2 - 25,
    resizeMode: 'contain',
  },
  subContainer: {
    padding: 5,
    width: '100%',
    marginTop: 'auto',
  },
  bottomContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productNameContainer: {
    height: 35,
  },
  cargoStatusContainer: {
    borderWidth: 1,
    borderColor: '#69bc44',
    borderRadius: 4,
    padding: 2,
    width: 50,
  },
  percentageStatusContainer: {
    borderWidth: 1,
    borderColor: COLORS.mainRed,
    backgroundColor: COLORS.mainRed,
    borderRadius: 4,
    padding: 2,
    marginTop: 5,
    width: 50,
  },
  percentageText: {
    textAlign: 'center',
    fontSize: 12,
    color: COLORS.mainWhite,
  },
  cargoText: {
    textAlign: 'center',
    fontSize: 7,
    color: '#69bc44',
  },
  outOfStockContainer: {
    // position: 'absolute',
    // left: 0,
    // top: '50%',
    // backgroundColor: '#D8BF7C',
    // paddingVertical: 4,
    // paddingHorizontal: 10,
    // width: 120,
    // transform: [{rotateZ: '90deg'}, {translateY: 48}],
    // borderTopLeftRadius: 10,
    // borderTopRightRadius: 10,
    width: '100%',
    backgroundColor: '#D8BF7C',
    borderRadius: 4,
    borderColor: '#D8BF7C',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  outOfStockText: {
    color: 'white',
    fontSize: 13,
  },
  differentVariantsContainer: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 4,
    borderColor: '#D8BF7C',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  differentVariantsText: {color: '#D8BF7C', fontSize: 11},
  fakeHeight: {
    height: 20,
  },
  productNewContainer: {
    padding: 10,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    ...globalStyles.smallShadow,
    borderRadius: 100,
    position: 'absolute',
    top: 10,
    right: 5,
  },
  productTypeContainer: {
    position: 'absolute',
    height: 20,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    ...globalStyles.smallShadow,
    right: 5,
    top: 10,
  },
  productVariantContainer: {
    position: 'absolute',
    height: 20,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    ...globalStyles.smallShadow,
    right: 5,
    top: 40,
  },
  productStatusContainer: {
    width: 50,
    alignItems: 'center',
    marginTop: 5,
  },
  productStatusText: {
    fontSize: 7,
    color: COLORS.mainPurple,
    textAlign: 'center',
  },
});
